nodeLinker: node-modules
enableGlobalCache: true
yarnPath: .yarn/releases/yarn-4.7.0.cjs

packageExtensions:
  "next@*":
    peerDependencies:
      "webpack": "*"
      "eslint": "*"
  "@next/swc-*@*":
    peerDependencies:
      "next": "*"
  "@storybook/nextjs@*":
    peerDependencies:
      "webpack": "*"
      "react-dom": "*"