enableGlobalCache: false
nodeLinker: pnp
pnpMode: strict
yarnPath: .yarn/releases/yarn-4.7.0.cjs

packageExtensions:
  "next@*":
    peerDependencies:
      "webpack": "*"
      "eslint": "*"
  "@next/swc-*@*":
    peerDependencies:
      "next": "*"