global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['$EC2_PUBLIC_HOST:$PROMETHEUS_PORT']

  - job_name: 'node'
    static_configs:
      - targets: ['$EC2_PUBLIC_HOST:$NODE_EXPORTER_PORT']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['$EC2_PUBLIC_HOST:$CADVISOR_PORT']

  - job_name: 'backend-stable'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['$EC2_PUBLIC_HOST:$STABLE_BACKEND_PORT']

  - job_name: 'backend-canary'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['$EC2_PUBLIC_HOST:$CANARY_BACKEND_PORT']