export interface SeatProps {
  seatId: number;
  arenaId: number;
  sectionId: number;
  row: number;
  col: number;
  isScraped: boolean;
  isScrapMode: boolean;
  isSelected: boolean;
}

export const seats: SeatProps[] = [
  // Arena 1, Section 101
  {
    seatId: 1,
    arenaId: 1,
    sectionId: 1,
    row: 1,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  {
    seatId: 2,
    arenaId: 1,
    sectionId: 1,
    row: 1,
    col: 2,
    isScraped: true,
    isScrapMode: false,
    isSelected: true,
  },
  {
    seatId: 3,
    arenaId: 1,
    sectionId: 1,
    row: 2,
    col: 1,
    isScraped: false,
    isScrapMode: true,
    isSelected: false,
  },
  // Arena 1, Section 102
  {
    seatId: 4,
    arenaId: 1,
    sectionId: 1,
    row: 3,
    col: 2,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  {
    seatId: 5,
    arenaId: 1,
    sectionId: 102,
    row: 1,
    col: 2,
    isScraped: false,
    isScrapMode: true,
    isSelected: true,
  },
  // Arena 2, Section 201
  {
    seatId: 6,
    arenaId: 2,
    sectionId: 201,
    row: 1,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  {
    seatId: 7,
    arenaId: 2,
    sectionId: 201,
    row: 1,
    col: 2,
    isScraped: false,
    isScrapMode: true,
    isSelected: true,
  },
  {
    seatId: 8,
    arenaId: 2,
    sectionId: 201,
    row: 2,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  // Arena 2, Section 202
  {
    seatId: 9,
    arenaId: 2,
    sectionId: 202,
    row: 1,
    col: 1,
    isScraped: false,
    isScrapMode: true,
    isSelected: true,
  },
  {
    seatId: 10,
    arenaId: 2,
    sectionId: 202,
    row: 1,
    col: 2,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  // Arena 3, Section 301
  {
    seatId: 11,
    arenaId: 3,
    sectionId: 301,
    row: 1,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: true,
  },
  {
    seatId: 12,
    arenaId: 3,
    sectionId: 301,
    row: 1,
    col: 2,
    isScraped: false,
    isScrapMode: true,
    isSelected: false,
  },
  {
    seatId: 13,
    arenaId: 3,
    sectionId: 301,
    row: 2,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: true,
  },
  // Arena 3, Section 302
  {
    seatId: 14,
    arenaId: 3,
    sectionId: 302,
    row: 1,
    col: 1,
    isScraped: false,
    isScrapMode: true,
    isSelected: false,
  },
  {
    seatId: 15,
    arenaId: 3,
    sectionId: 302,
    row: 1,
    col: 2,
    isScraped: true,
    isScrapMode: false,
    isSelected: true,
  },
  // Arena 4, Section 401
  {
    seatId: 16,
    arenaId: 4,
    sectionId: 401,
    row: 1,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  {
    seatId: 17,
    arenaId: 4,
    sectionId: 401,
    row: 1,
    col: 2,
    isScraped: false,
    isScrapMode: true,
    isSelected: true,
  },
  // Arena 4, Section 402
  {
    seatId: 18,
    arenaId: 4,
    sectionId: 402,
    row: 1,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
  {
    seatId: 19,
    arenaId: 4,
    sectionId: 402,
    row: 1,
    col: 2,
    isScraped: false,
    isScrapMode: true,
    isSelected: true,
  },
  {
    seatId: 20,
    arenaId: 4,
    sectionId: 402,
    row: 2,
    col: 1,
    isScraped: true,
    isScrapMode: false,
    isSelected: false,
  },
];
