export interface SectionProps {
  sectionId: number;
  arenaId: number;
  sectionName: string;
  isScraped: boolean;
  onClick?: () => void;
  startAngle: number;
  endAngle: number;
  innerRadius: number;
  outerRadius: number;
  isScrapMode: boolean;
}

export const sections: SectionProps[] = [
  {
    sectionId: 1,
    arenaId: 1,
    sectionName: '001',
    isScraped: false,
    startAngle: 0,
    endAngle: 30,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 2,
    arenaId: 1,
    sectionName: '002',
    isScraped: true,
    startAngle: 30,
    endAngle: 60,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 3,
    arenaId: 1,
    sectionName: '003',
    isScraped: false,
    startAngle: 60,
    endAngle: 90,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 4,
    arenaId: 1,
    sectionName: '004',
    isScraped: false,
    startAngle: 90,
    endAngle: 120,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 5,
    arenaId: 1,
    sectionName: '005',
    isScraped: true,
    startAngle: 120,
    endAngle: 150,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 6,
    arenaId: 1,
    sectionName: '111',
    isScraped: false,
    startAngle: 150,
    endAngle: 180,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 7,
    arenaId: 1,
    sectionName: '110',
    isScraped: true,
    startAngle: 180,
    endAngle: 210,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 8,
    arenaId: 1,
    sectionName: '109',
    isScraped: false,
    startAngle: 210,
    endAngle: 240,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 9,
    arenaId: 1,
    sectionName: '108',
    isScraped: true,
    startAngle: 240,
    endAngle: 270,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 10,
    arenaId: 1,
    sectionName: '107',
    isScraped: false,
    startAngle: 270,
    endAngle: 300,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 11,
    arenaId: 1,
    sectionName: '106',
    isScraped: false,
    startAngle: 300,
    endAngle: 330,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 12,
    arenaId: 1,
    sectionName: '105',
    isScraped: true,
    startAngle: 330,
    endAngle: 360,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 13,
    arenaId: 1,
    sectionName: '235',
    isScraped: false,
    startAngle: 0,
    endAngle: 90,
    innerRadius: 100,
    outerRadius: 150,
    isScrapMode: false,
  },
  {
    sectionId: 14,
    arenaId: 1,
    sectionName: '234',
    isScraped: true,
    startAngle: 90,
    endAngle: 180,
    innerRadius: 100,
    outerRadius: 150,
    isScrapMode: false,
  },
  {
    sectionId: 15,
    arenaId: 1,
    sectionName: '233',
    isScraped: false,
    startAngle: 180,
    endAngle: 270,
    innerRadius: 100,
    outerRadius: 150,
    isScrapMode: false,
  },
  {
    sectionId: 16,
    arenaId: 1,
    sectionName: '232',
    isScraped: true,
    startAngle: 270,
    endAngle: 360,
    innerRadius: 100,
    outerRadius: 150,
    isScrapMode: false,
  },
  {
    sectionId: 12,
    arenaId: 2,
    sectionName: '105',
    isScraped: true,
    startAngle: 0,
    endAngle: 72,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 13,
    arenaId: 2,
    sectionName: '235',
    isScraped: false,
    startAngle: 72,
    endAngle: 144,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 14,
    arenaId: 2,
    sectionName: '234',
    isScraped: true,
    startAngle: 144,
    endAngle: 216,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 15,
    arenaId: 2,
    sectionName: '233',
    isScraped: false,
    startAngle: 216,
    endAngle: 288,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
  {
    sectionId: 16,
    arenaId: 2,
    sectionName: '232',
    isScraped: true,
    startAngle: 288,
    endAngle: 360,
    innerRadius: 50,
    outerRadius: 100,
    isScrapMode: false,
  },
];
